namespace Modules.Navigation
{
    public enum NavigationElementType
    {
        Unknown = 0,
        AssetsScreen = 1,
        OccupationScreen = 2,
        CharacterAsset = 3,
        CharacterAssetProfile = 4,
        FinancesProfile = 5,
        SocialDirectory = 6,
        Shopping = 7,
        SocialNetwork = 8,
        RelationshipsScreen = 9,
        ActivitiesScreen = 10,
        CurrentOccupationScreen = 11,
        NpcScreen = 12,
        FlirtInteraction = 13,
        BeFriendInteraction = 14,
        CommunicationInteraction = 15,
        ChatInteraction = 16,
        GiftInteraction = 17,
        InsultInteraction = 18,
        FightInteraction = 19,
        AskMoneyInteraction = 20,
        ComplimentInteraction = 21,
        FindJobScreen = 22,
        Vacancy = 23,
        CurrentOccupationProfile = 24,
        ColleaguesDirectory = 25,
        Schedule = 26,
        Resign = 27,
        FullTimeJobs = 28,
        FindPartTimeJob = 29,
        SchoolDropOut = 30,
        SchoolFaculty = 31,
        SchoolNurse = 32,
        SchoolLibrary = 33,
        SchoolAdministration = 34,
        SchoolStudyHarder = 35,
        SchoolSkip = 36,
        UnFriendInteraction = 37,
        DateInteraction = 38,
        AskOutInteraction = 39,
        WorkHarder = 40,
        SkipWork = 41,
        SexInteraction = 42,
        SpendTimeInteraction = 43,
        MainScreen = 44,
        
        Menu = 45,
        MenuSound = 46,


        Military = 47,

        AirForce = 48,
        Army = 49,
        CostGueards = 50,
        Marines = 51,
        Navy = 52,

        Recruit = 53,
        WarrantOfficer = 54,
        Officer = 55,
        VacancyArmy = 56,
        Desertion = 57,
        ExtendContract = 58,
        Retire = 59,
        PartTimeVacancy = 60,
        SkipPartTimeWork = 61
    }
}